version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: myapp_development
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - /app/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true